import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/nav/NavBar";
import Content from "@/components/layout/nav/Content";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Creative components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.variable}  antialiased `}>
        <main className="absolute top-0 left-0 w-screen h-screen bg-neutral-950 text-neutral-200 flex justify-center items-center py-10">
          <div className="relative z-50 w-4/5 h-full flex gap-4">
            <NavBar />
            <Content />
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
